apiVersion: v2
name: unikorn-ui
description: A Helm chart for deploying Unikorn UI

type: application

version: v0.2.1
appVersion: v0.2.1

icon: https://raw.githubusercontent.com/eschercloudai/unikorn/main/icons/default.png
